[package]
edition = "2021"
name = "de"
version = "0.1.0"

[profile.release]
panic = "abort"
strip = true
opt-level = "z"
codegen-units = 1

[dependencies]
anyhow = "1"
clap = { version = "3.1", default-features = false, features = ["std"] }
crossbeam-channel = "0.5"
